version: '3.4'
services:
  mongo:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes: 
      - $PWD/mongo:/data/db
    networks:
      - project-network
  redis:
    image: redis
    volumes: 
      - $PWD/redis:/data
    ports:
      - "6379:6379"
    networks:
      - project-network
networks:
  project-network:
    external: true
